openapi: 3.0.0
info:
  title: Mars Trading Platform
  description: A Backend Developer technical exam from the client at ThriveNow PH
  version: 1.0.0
servers:
  - url: http://localhost:8000
tags:
  - name: Martians
    description: Martian functionalities
  - name: Products
    description: Product functionalities
  - name: Inventories
    description: Martian Inventory and Supplies
  - name: Trade
    description: Martian Inventory and Supplies Trading
paths:
  /api/martians:
    description: Martian Resource
    post:
      tags:
        - Martians
      description: Create Martian
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: number
                gender:
                  type: string
                can_trade:
                  type: boolean
            examples:
              example-1:
                value:
                  name: John Doe
                  age: 34
                  gender: M
                  can_trade: true
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/martian"

    get:
      tags:
        - Martians
      description: Martian List
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/martian_inventories"

  /api/martians/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        description: Unique martian identifier.
        required: true
    description: Martian Resource
    get:
      tags:
        - Martians
      description: Get Martian Information
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/martian_inventories"
        404:
          description: Not Found Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    put:
      tags:
        - Martians
      description: Update Martian Information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: number
                gender:
                  type: string
                can_trade:
                  type: boolean
            examples:
              example-1:
                value:
                  name: John Doe
                  age: 34
                  gender: M
                  can_trade: false
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/martian"
        404:
          description: Not Found Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/products:
    description: Product Resource
    post:
      tags:
        - Products
      description: List Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                points:
                  type: number
            examples:
              example-1:
                value:
                  name: Mystery Box
                  points: 10
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/product"
    get:
      tags:
        - Products
      description: Product List
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/product"
  /api/products/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        description: Unique product identifier.
        required: true
    description: Product Resource
    get:
      tags:
        - Products
      description: Get Product Details
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/product"
    put:
      tags:
        - Products
      description: Update Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                points:
                  type: number
            examples:
              example-1:
                value:
                  name: Mystery Box
                  points: 10
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/product"

  /api/martians/{martianId}/inventories:
    parameters:
      - schema:
          type: string
        name: martianId
        in: path
        description: Unique martian identifier.
        required: true
    description: Inventory Resource
    get:
      tags:
        - Inventories
      description: Get Martian Inventory Information
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/inventory"

  /api/martians/{martianId}/inventories/{id}:
    parameters:
      - schema:
          type: string
        name: martianId
        in: path
        description: Unique martian identifier.
        required: true
      - schema:
          type: string
        name: id
        in: path
        description: Unique inventory identifier.
        required: true
    description: Inventory Resource
    get:
      tags:
        - Inventories
      description: Get Martian Inventory Information
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/inventory"

  /api/martians/inventories:
    description: Martian Resource
    post:
      tags:
        - Inventories
      description: Create Martian Inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                martian_id:
                  type: number
                product_id:
                  type: number
                qty:
                  type: number
            examples:
              example-1:
                value:
                  martian_id: 1
                  product_id: 2
                  qty: 5
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/inventory"
        400:
          description: Error Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/martians/inventories/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        description: Unique inventory identifier.
        required: true
    description: Inventory Resource
    put:
      tags:
        - Inventories
      description: Update Martian Inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                martian_id:
                  type: number
                qty:
                  type: number
            examples:
              example-1:
                value:
                  martian_id: 1
                  qty: 5
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/inventory"
        400:
          description: Error Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/martians/trade:
    description: Trade Resource
    post:
      tags:
        - Trade
      description: Martian Trading
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                martian_id:
                  type: number
                items:
                  type: array
                  items:
                    properties:
                      item_id:
                        type: number
                      qty:
                        type: number
                right_trader:
                  type: object
                  properties:
                    martian_id:
                      type: number
                    items:
                      type: array
                      items:
                        properties:
                          item_id:
                            type: number
                          qty:
                            type: number
            examples:
              example-1:
                value:
                  martian_id: 1
                  items: [{ item_id: 1, qty: 1 }]

                  right_trader:
                    martian_id: 2
                    items:
                      [
                        { item_id: 3, qty: 1 },
                        { item_id: 4, qty: 1 },
                        { item_id: 5, qty: 1 },
                      ]
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    product:
      type: object
      properties:
        name:
          type: string
        points:
          type: number
        created_at:
          type: string
        updated_at:
          type: string
    inventory:
      type: object
      properties:
        id:
          type: number
        martian_id:
          type: number
        product_id:
          type: number
        qty:
          type: number
        product:
          type: object
          properties:
            name:
              type: string
            points:
              type: number
            created_at:
              type: string
            updated_at:
              type: string
    martian:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        gender:
          type: number
        can_trade:
          type: number
        created_at:
          type: string
        updated_at:
          type: string
    martian_inventories:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        gender:
          type: number
        can_trade:
          type: number
        created_at:
          type: string
        updated_at:
          type: string
        inventories:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
              martian_id:
                type: number
              name:
                type: string
              points:
                type: number
              created_at:
                type: string
              updated_at:
                type: string
