version: "3"
services:
  mysql:
    image: mysql
    container_name: martian_db
    ports:
      - 33067:3306
    environment:
      MYSQL_DATABASE: martian_db
      MYSQL_ROOT_PASSWORD: root
    # volumes:
    #   - ./data:/var/lib/mysql

  app:
    image: martian_app
    container_name: martian_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      APP_ENV: local
      CONTAINER_ROLE: martian_app

  nginx:
    image: nginx:alpine
    container_name: martian_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 8000:80
